name: wbs_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  sizer: ^3.0.4
  persistent_bottom_nav_bar: ^5.0.2
  simple_animations: ^4.2.0
  flutter_native_splash: ^2.4.3
  flutter_spinkit: ^5.2.1
  loader_overlay: ^4.0.3
  go_router: ^14.6.1
  file_picker: ^8.1.6
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  strings: ^0.2.2
  fluttertoast: ^8.2.8
  intl: ^0.19.0
  byte_converter: ^2.0.0
  shimmer: ^3.0.0
  fluro: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#0064D9"
  android_12:
    color: "#0064D9"
  
flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/image/
    - assets/icon/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
